name: kwant-stable-no-extras
channels:
    - conda-forge
dependencies:
    - python=3.6
    - numpy=1.13.1
    - scipy=0.19.1
    - tinyarray=1.2.0
    # Linear algebra libraraies
    - blas #=1.1 openblas
    - openblas #=0.2.20
    # Build toolchain
    - toolchain3
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
