name: kwant-stable-no-extras
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16.2
    - scipy=1.1.0
    - tinyarray=1.2
    # Linear algebra libraraies
    - blas #=1.1 openblas
    - openblas #=0.2.20
    # Build toolchain
    - toolchain3
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
