name: kwant-latest
channels:
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - numpy
    - scipy
    - tinyarray
    - sympy
    - matplotlib-base
    - plotly
    - qsymm
    # Linear algebra libraries
    # Pin mumps due to switching int size in 5.5.1
    - mumps-seq=5.2.1
    # Pin metis due to ABI incompatibility in 5.1.1
    # See https://github.com/conda-forge/mumps-feedstock/issues/87
    - metis=5.1.0
    - blas
    - openblas
    # Build toolchain
    - compilers
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
    # Documentation building
    - sphinx
    - numpydoc
    - requests
    - sphinx-book-theme
    - jupyter-sphinx
    - sphinx-togglebutton
    - pip:
        - sphinxcontrib-svg2pdfconverter
