name: kwant-stable
channels:
    - conda-forge
dependencies:
    - python=3.6
    - numpy=1.13.3
    - scipy=0.19.1
    - tinyarray=1.2.0
    - sympy=1.1.1
    - matplotlib=2.1.1
    - qsymm=1.2.6
    - plotly=2.2.2
    # Linear algebra libraraies
    - mumps
    - blas #=1.1 openblas
    - openblas #=0.2.20
    # Build toolchain
    - toolchain3
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
