name: kwant-stable
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16.2
    - scipy=1.1.0
    - tinyarray=1.2
    - sympy=1.3.0
    - matplotlib-base=3.0.2
    - plotly=3.6.1
    - qsymm=1.3.0
    # Linear algebra libraraies
    - mumps
    - blas #=1.1 openblas
    - openblas #=0.2.20
    # Build toolchain
    - toolchain3
    - cython
    - libgfortran
    ## Dev Dependencies
    # Testing
    - pytest
    - pytest-cov
    - pytest-flakes
    - pytest-pep8
